### ISSUE TITLE
Content Request - Kamigawa Race - Kitsune

### ISSUE THREAD

**Issue by Belusrey** [community-elements/elements-dndwiki#18]
I would love to see this implemented, as i'm to unexperienced to make a working .xml on my own... :(

https://drive.google.com/file/d/1A8DCgBa3WkpQNxOMAn8sYGNrB5kJwZT8/view

A link to the source of the requested content. (website or pdf)

**Comment by NickVendel** [comment]
Kor Artificer's homebrew isn't a part of D&DWiki. and so will not be included in.
